(defconst end-tag-id 0)
(defconst byte-tag-id 1)
(defconst short-tag-id 2)
(defconst int-tag-id 3)
(defconst long-tag-id 4)
(defconst float-tag-id 5)
(defconst double-tag-id 6)
(defconst byte-array-tag-id 7)
(defconst string-tag-id 8)
(defconst tag-list-tag-id 9)
(defconst start-compound-tag-id 10)
(defconst int-array-tag-id 11)
(defconst long-array-tag-id 12)

(provide 'nbt-tags-id)
